name: jobbeer_flutter
description: As melhores vagas para programadores reúnidas em um único app!

version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.3
  rxdart: ^0.22.3
  bloc_pattern: ^2.4.2+1
  shared_preferences: ^0.5.4+3
  flutter_screenutil: ^0.6.0
  url_launcher: ^5.2.5
  intl: ^0.16.0
  admob_flutter: ^0.3.4
  animated_text_kit: ^1.3.1
  firebase_analytics: ^5.0.2
  esys_flutter_share: ^1.0.2
  firebase_dynamic_links: ^0.5.0+8

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/jobbeer_logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/assets/fonts/Pacifico-Regular.ttf